config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  devise_for :users
  get 'update_task_status', to: 'tasks#update_task_status'
  get 'filter_task_day', to: 'tasks#filter_task_day'
  get 'task_activity', to: 'task_activity#index', as: 'task_activity'

  get 'task_update', to: 'tasks#task_update'
  get 'profile', to: 'home#profile'

  get 'show_task_details', to: 'tasks#show_task_details'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user

	attribute :task_color, :string, default: 'bg-primary text-white'
	attribute :task_status, :boolean, default: false

	attribute :email_sent_for_due_date_missed, :boolean, default: false
    attribute :email_sent_for_due_date_tomorrow, :boolean, default: false


	def self.check_missed_tasks
		Rails.logger.info "Running check_missed_tasks"
		missed_tasks = where('task_day < ? AND task_status = ?', Date.today, false)
		missed_tasks.each do |task|
		  UserMailer.missed_task_alert(task.user, task).deliver_now
		  Rails.logger.info "Sent missed task alert to #{task.user.email} for task #{task.task_name}"
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper :all

	def total_task
		Task.all
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = current_user.tasks.all
  end

  def profile
    @tasks = current_user.tasks.all
    @high_priorty_tasks = current_user.tasks.where(task_priority: 'High')
  end
end

app/controllers/task_activity_controller.rb
class TaskActivityController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    date = (Date.today)
    @tasks = current_user.tasks.where(task_day: date)
    tomorrow = Date.today+1
    @tasks_day_after_tomorrow = current_user.tasks.where('task_day > ?' , tomorrow)
  end

  
  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.new
    respond_to do |format|
      format.js { render 'tasks/new' }
    end
  end

  # GET /tasks/1/edit
  def edit
    # respond_to do |format|
    #   format.js { render  "tasks/edit" }  
    # end
  end

  # POST /tasks or /tasks.json
  def create
    # get_day = check_task_day(params[:task_day])
    @task = current_user.tasks.new(task_name: params[:task_name], task_description: params[:task_description], task_priority: params[:task_priority],task_color: params[:task_color], task_day: params[:task_day] )
    if @task.save
      respond_to do |format|
        # format.js { render 'tasks/create' }
        format.html { redirect_to tasks_path }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    # get_day = check_task_day(params[:task][:task_day])
    respond_to do |format|
      if @task.update(task_name: params[:task][:task_name], task_description: params[:task][:task_description], task_priority: params[:task][:task_priority], task_day: params[:task][:task_day], task_color: params[:task_color] )
        # @tasks = current_user.tasks.where(task_day: get_day)
        format.js { render 'tasks/task_update' }
      else
        redirect_to root_path
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    task_day = current_user.tasks.find(params[:id]).task_day
    @tasks = current_user.tasks.where(task_day: task_day)
    @task.destroy
    respond_to do |format|
      format.js { render 'tasks/task_update' }
    end
  end

  # def check_task_day(day)
  #   if day == "Day After Tomorrow"
  #     date = Date.today
  #     return (date+2).to_s
  #   elsif day == "Tomorrow"
  #     date = Date.today
  #     return (date+1).to_s
  #   else
  #     return (Date.today).to_s
  #   end
  # end
  
  def update_task_status
    task = Task.find(params[:task_id])
    task.task_status = params[:task_status].eql?('1')
    task.save
    date = task.task_day
    if date == Date.today
      @tasks = current_user.tasks.where(task_day: date)   
    elsif date == Date.today + 1
      @tasks = current_user.tasks.where(task_day: date)
    elsif date == Date.today - 1
      @tasks = current_user.tasks.where(task_day: date )
    else
      @tasks = current_user.tasks.where('task_day > ?', Date.today + 1)
    end
    respond_to do |format|
      format.js { render partial: 'tasks/show_tasks', locals: { tasks: @tasks } }
    end
  end
      
  def filter_task_day
    get_filter_day = params[:filter_day]
    if get_filter_day == 'after_tomorrow'
      tomorrow = Date.today + 1
      @tasks = current_user.tasks.where('task_day > ?', tomorrow)
    else
      @tasks = current_user.tasks.where(task_day: get_filter_day)
    end

    respond_to do |format|
      format.js { render 'tasks/task_filter_by_day' }
    end
  end
  
  def task_update
    @task = current_user.tasks.find(params[:id])
    task_day = @task.task_day
    respond_to do |format|
      format.js { render 'tasks/edit' }
    end
  end
  
  def show_task_details
    @task = current_user.tasks.find(params[:task_id])
    respond_to do |format|
      format.js
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task_name, :task_description, :task_priority, :task_day, :task_color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def total_task
		current_user.tasks.all.count
	end

	# day task analysis
	def today_task
		current_user.tasks.where('task_day = ?', (Date.today).to_s ).count
	end
	
	def today_task_uncomplete
		current_user.tasks.where(["task_day = ? and task_status = ? ", (Date.today).to_s , false]).count
	end

	def today_task_completed
		current_user.tasks.where(["task_day = ? and task_status = ? ", (Date.today).to_s , true]).count
	end
	
	# week task analysis
	def this_weak_task
		current_user.tasks.where('task_day >= ?', 1.week.ago).count
	end
	
	def task_uncomplete
		current_user.tasks.where(task_status: false).count
	end

	def task_completed
		current_user.tasks.where(task_status: true).count
	end

	def show_edit_task_day(day_date)
		date = Date.today
		if day_date == date.to_s
			return "Today"
		elsif day_date == (date+1).to_s
			return "Tomorrow"
		elsif day_date == (date+2).to_s
			return "Day After Tomorrow"
		end
	end
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_activity_helper.rb
module TaskActivityHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<div class="container">
	<%= link_to "Add task", tasks_path %>
	<!-- Button trigger modal -->
	<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
		Launch demo modal
	</button>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md container">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
				<% if user_signed_in? %>
               		<%= link_to "#{current_user.email}", root_path %>
				<% else %>	
					<span>Welcome user! </span>
				<% end %>		   
            </li>
        </ul>
    </div>
    <div class="w-100 order-0 d-lg-none">
		<div class="d-flex justify-content-between">
			<div>
				<span class="text-primary"><%= current_user.name if user_signed_in?  %></span>
			</div>
			<div>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
					<span class="navbar-toggler-icon"></span>
				</button>
			</div>
		</div>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
			<% if user_signed_in? %>
				<li class="nav-item">
					<%= link_to "Logout", destroy_user_session_path, class:'nav-link' ,method: :delete%>
				</li>
			<% else %>
				<li class="nav-item">
					<%= link_to "Signup", new_user_registration_path, class:'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to "Login", new_user_session_path, class:'nav-link' %>
				</li>
			<% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTaskManage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </head>

  <body class="bg-light">
    <%= render 'layouts/nav' %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/task_activity/index.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>

<div class="container">
	<!--render sub navigation bar -->
  <%= render 'tasks/sub_nav' %>

	<!-- Task add Modal -->
  <%= render partial: 'tasks/new_task_add_modal' %>

	<!-- <div class="h3 text-primary">Welcome in new task managment system.</div> -->
	<div class="container w-100">
		<div class="shadow col-12 w-100 p-4 rounded ">
			<div class="h2 text-primary">Today Task 📌</div>
			<div class="row mt-5">
				<div class="col-sm-4 text-center">
					<div class="h5">
						<div>Today all task</div>
						<div class="mt-2"><%= today_task %></div>
					</div>
					<div>
					</div>
				</div>
				<div class="col-sm-4 text-center h5">
					<div>Tasks completed</div>
					<div class="mt-2"><%= today_task_completed %></div>
				</div>
				<div class="col-sm-4 text-center h5">
					<div>Tasks uncompleted</div>
					<div class="mt-2"><%= today_task_uncomplete %></div>
				</div>
			</div>
		</div>

		<div class="shadow col-12 w-100 p-4 rounded mt-5 mb-3">
			<div class="h2 text-primary">This week analysis 📊 🚀</div>
			<div class="row mt-5">
				<div class="col-sm-4 text-center">
					<div class="h5">
						<div>This week Tasks</div>
						<div class="mt-2"><%= this_weak_task %></div>
					</div>
					<div>
					</div>
				</div>
				<div class="col-sm-4 text-center h5">
					<div>Tasks completed</div>
					<div class="mt-2"><%= task_completed %></div>
				</div>
				<div class="col-sm-4 text-center h5">
					<div>Tasks uncompleted</div>
					<div class="mt-2"><%= task_uncomplete %></div>
				</div>
			</div>
			<div class="mt-5">
				<%= line_chart @tasks.group_by_day_of_week(:task_day,format: "%a").count %>
				<div class="text-center mt-3 text-secondary h5">Task assign in daily bases</div>
			</div>
		</div>
	</div>
</div>

app/views/tasks/_edit_task_form.html.erb
<div class="modal fade" id="show-edit-tasks-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: @task, local: false) do |f| %>
          <% if @task.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
              <ul>
                <% @task.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="modal-body">
            <div class="container">
              <div class="mt-2">
                <%= f.text_field :task_name, class: 'form-control' %>
              </div>
              <div class="mt-4">
                <%= f.text_area(:task_description, size: '50x10', class: 'form-control') %>
              </div>
              <div class="mt-4">
                <div class="row">
                  <div class="col-sm-6"> 
                    <%= f.label :task_priority %> 
                    <p class="form-control">
                    <%= f.select(:task_priority, ["Low", "High", "Medium"], class: 'form-control')  %>
                    </p>
                  </div>
                  <div class="col-sm-6"> 
                    <%= f.label :task_day %> 
                    <%= f.date_field :task_day , class: 'form-control'  %>
                  </div>
                </div>
              </div>
              <hr>  
              <div class="container">
                <label for="">Select color for task</label>
                <div class="row " id=show-color"">
                 <div class="col-1 mr-2 bg-primary rounded-circle p-4 h-75 c-option" onclick="setCheckColor(this ,'bg-primary text-white')"></div>
                  <div class="col-1 mr-2 bg-success rounded-circle p-4 h-75 c-option" onclick="setCheckColor(this, 'bg-success text-white')"></div>
                  <div class="col-1 mr-2 bg-info rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'bg-info text-white')"></div>
                  <div class="col-1 mr-2 fifth-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'fifth-color text-white')"></div>

                  <div class="col-1 mr-2 first-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'first-color text-white')"></div>
                  <div class="col-1 mr-2 fourth-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'fourth-color text-white')"></div>
                  <div class="col-1 mr-2 third-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'third-color text-white')"></div>
                </div>
                <div id="select-color">
                    <%= hidden_field_tag :task_color, "" ,id:'select-c'%>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.submit "Update task", class:'btn btn-primary' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_new_task_add_modal.html.erb
<div class="modal fade" id="addTask" tabindex="-1" aria-labelledby="addTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= form_with url: "/tasks", method: :post, remote: true do |f| %>
          <div class="modal-body">
            <div class="container">
              <div class="mt-2">
                <%= f.text_field :task_name, placeholder: "Enter task name", class: 'form-control' %>
              </div>
              <div class="mt-4">
                <%= f.text_area(:task_description, size: '50x10',  placeholder: "Enter task Desciption", class: 'form-control') %>
              </div>
              <div class="mt-4">
                <div class="row">
                  <div class="col-sm-6">
                    <%= f.label :task_priority %> 
                    <%= f.select(:task_priority, ["Low", "High", "Medium"], { selected: "Low" }, {required: 'true', class: 'form-control'})  %>
                  </div>
                  <div class="col-sm-6"> 
                    <%= f.label :task_day %> 
                    <%= f.date_field :task_day , class: 'form-control'  %>
                  </div>
                </div>
              </div>
              <hr>  
              <div class="container">
                <label for="">Select color for task</label>
                <div class="row " id=show-color"">
                  <div class="col-1 mr-2 bg-primary rounded-circle p-4 h-75 c-option" onclick="setCheckColor(this ,'bg-primary text-white')"></div>
                  <div class="col-1 mr-2 bg-success rounded-circle p-4 h-75 c-option" onclick="setCheckColor(this, 'bg-success text-white')"></div>
                  <div class="col-1 mr-2 bg-info rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'bg-info text-white')"></div>
                  <div class="col-1 mr-2 fifth-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'fifth-color text-white')"></div>

                  <div class="col-1 mr-2 first-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'first-color text-white')"></div>
                  <div class="col-1 mr-2 fourth-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'fourth-color text-white')"></div>
                  <div class="col-1 mr-2 third-color rounded-circle p-4 h-50 c-option" onclick="setCheckColor(this, 'third-color text-white')"></div>
                </div>
                <div id="select-color">
                    <%= hidden_field_tag :task_color, "" ,id:'select-c'%>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.submit "save task", class:'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/tasks/_show_tasks.html.erb
<% if @tasks.empty? %>
  <span class="text-secondary h4">There are no tasks</span>
<% else %>
  <div>
    <div class="">
      <div class="h3 text-danger">Uncompleted Tasks</div>
      <div class="row">
        <% @tasks.each do |task| %>
          <% unless task.task_status? %>
            <div class="show-task p-3 rounded shadow-lg m-4 col-sm-5 <%= task.task_color %>">
              <div class="task-title cursor-pointer" id="<%=task.id%>" onclick="show_task_details(this)">
                <% if task.task_priority == 'High' %>
                  <b class="priorty text-danger"><%= task.task_priority %></b>
                <% elsif task.task_priority == 'Medium' %>
                  <b class="priorty text-warning"><%= task.task_priority %></b>  
                <% else %>
                  <b class="priorty text-dark m-1"><%= task.task_priority %></b>   
                <% end %>  
                <span class="task-detail h3 "><%= task.task_name %></span>
                <p class="task-detail"><%= task.task_description %></p>
              </div>
              <div class="row border-top pt-2 d-flex task-op">
                <div class="col-3">
                  <%= link_to "Delete", task_path(task), method: :delete, remote: true, class:'text-white task-delete-link' %>
                </div>
                <div class="col-3">
                  <%= link_to "Edit", task_update_path(id: task.id), remote: true, class:'text-white task-edit-link' %>
                </div>
                <div class="col-6 text-right">
                  <input type="checkbox" name="task_status" id="<%= task.id %>" class="t_status" onchange="update_task_s(this)" >
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="">
      <hr>
      <div class="h3 text-primary">Completed Task</div>
      <div class="row">
        <% @tasks.each do |task| %>
          <% if task.task_status? %>
            <div class="show-task p-3 rounded shadow-lg m-4 col-sm-5 <%= task.task_color %>">
              <div class="task-title cursor-pointer" id="<%=task.id%>" onclick="show_task_details(this)">
                <% if task.task_priority == 'High' %>
                  <b class="priorty text-danger"><%= task.task_priority %></b>
                <% elsif task.task_priority == 'Medium' %>
                  <b class="priorty text-warning"><%= task.task_priority %></b>  
                <% else %>
                  <b class="priorty text-info m-1"><%= task.task_priority %></b>   
                <% end %>  
                <span class="task-detail h3"><%= task.task_name %></span>
                <p class="task-detail"><%= task.task_description %></p>
              </div>
              <div class="row border-top pt-2 d-flex task-op">
                <div class="col-3">
                  <%= link_to "Delete", task_path(task), method: :delete, remote: true, class:'text-white task-delete-link' %>
                </div>
                <div class="col-3">
                  <%= link_to "Edit", task_update_path(id: task.id), remote: true, class:'text-white task-edit-link' %>
                </div>
                <div class="col-6 text-right">
                  <input type="checkbox" name="task_status" id="<%= task.id %>" class="t_status" onchange="update_task_s(this)" checked>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_sub_nav.html.erb
<ul class="nav justify-content-around align-items-center">
  <li class="nav-item d-flex align-items-center text-secondary h4">
    <span class="mr-1"><%= fa_icon 'university 1x' %></span>
    <%= link_to "Dashboard", root_path ,class:'nav-link h4 mt-1 text-secondary' %>
  </li>
  <li class="nav-item d-flex align-items-center ">
    <a class="nav-link active align-item-center h4 text-secondary" data-bs-toggle="modal" data-bs-target="#addTask" aria-current="page" href="#"><span class="mr-1"><%= fa_icon 'plus 1x' %></span> New Task</a>
  </li>
  <li class="nav-item d-flex align-items-center text-secondary h4">
    <span class="mr-1"><%= fa_icon 'line-chart 1x' %></span>
    <%= link_to "Activity", task_activity_path ,class:'nav-link h4 mt-1 text-secondary' %>
  </li>
  <li class="nav-item d-flex align-items-center text-secondary h4">
    <span class="mr-1"><%= fa_icon 'user 1x' %></span>
    <%= link_to "Profile", profile_path ,class:'nav-link h4 mt-1 text-secondary' %>
  </li>
</ul>
<hr class="">

app/views/tasks/_task_detail_show_modal.html.erb
<div class="modal fade" id="showTaskDetails" tabindex="-1" aria-labelledby="addTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
		<div class="modal-header">
			<h5 class="modal-title h3" id="staticBackdropLabel">Task</h5>
			<span data-bs-dismiss="modal" class="h3 cursor-pointer" aria-label="Close"><%= fa_icon 'times 1x' %></span>
		</div>
		<% if @task.task_status %>
		   <p class="text-right text-success mr-2">⌛ <%= @task.task_day %></p>
		<% else %>
		   <p class="text-right text-danger mr-2">⏳ <%= @task.task_day %></p>
		<% end %>
		<div class="container">
			<div class="mt-4">
				<p class="h4"><%= @task.task_name %></p>
				<p class="mt-3"><%= @task.task_description %></p>
			</div>
			<div class="mt-2">
				<% if @task.task_status? %>
					<div class="alert alert-success h5" role="alert">
						This task is done 😉 ! 
					</div>
				<% else %>
					<div class="alert alert-danger h5" role="alert">
						This task is not done 🙁 !
						<% if @task.task_day < Date.today %>
						<br/><br>You missed this task ⛔ 🤬 !
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	  </div>
	</div>
</div>

app/views/tasks/create.js.erb
console.log("in index file")
document.querySelector('#show-tasks').innerHTML = '<%= j render 'tasks/_show_tasks.html.erb' %>'

app/views/tasks/edit.js.erb
document.querySelector('#show-edit-tasks').innerHTML = '<%= j render partial: 'tasks/edit_task_form.html.erb' %>'
$('#show-edit-tasks-modal').modal('show');

app/views/tasks/index.html.erb
<% if notice.present?%>
<div class="alert alert-success alert-dismissible fade show w-50 p-3 mx-auto" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<%= javascript_pack_tag "show_task" %>
<%= javascript_pack_tag "task_status_update" %>

<div class="container">
  <!--render sub navigation bar -->
  <%= render 'tasks/sub_nav' %>

  <div id="">
    <div class="row task-width">
      <div class="col-10" id="show-tasks">
        <div id="show-tasks">
         <%= render partial: 'tasks/show_tasks', locals: { tasks: @tasks } %>
        </div>
      </div>  
      <div class="col-2 mt-4 text-center p-4 d-none d-lg-block h-100 shadow rounded text-right" id="day-filter" style="">
        <% day = Date.today %>
        <div class=""><%= link_to "Yesterday", filter_task_day_path(filter_day: (day-1) ), remote: true, class:'h4 text-secondary filter-day', onclick: "change_color(this)" %></div>
        <div class="mt-3 pt-3 border-top"><%= link_to "Today", filter_task_day_path(filter_day: (day)), remote: true, class:'h4 text-primary filter-day', onclick: "change_color(this)" %></div>
        <div class="mt-3 pt-3 border-top"><%= link_to "Tomorrow", filter_task_day_path(filter_day: (day+1)), remote: true, class:'h4 text-secondary filter-day', onclick: "change_color(this)" %></div>
        <div class="mt-3 pt-3 border-top"> <%= link_to "Day After Tomorrow", filter_task_day_path(filter_day: 'after_tomorrow'), remote: true, class: 'h4 text-secondary filter-day', onclick: "change_color(this)" %></div>
      </div>
  </div> 

    
    <div id="show-edit-tasks">
    </div>
    <div id="show-task-details">
    </div> 
  </div>
  <!-- Task add Modal -->
  <%= render partial: 'tasks/new_task_add_modal' %>
  
</div>
<script>
  var get_all_color = document.getElementById('show-color');
  setCheckColor = (e, get_color) =>{
    e.classList.toggle('bg-dark')
    document.getElementById('select-c').value = get_color;
  }
</script>

app/views/tasks/new.js.erb
console.log("in new js file")
$('#addTask').modal('show');

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/show_task_details.js.erb
document.querySelector('#show-task-details').innerHTML = '<%= j render partial: 'tasks/task_detail_show_modal.html.erb' %>'
$('#showTaskDetails').modal('show');

app/views/tasks/task_filter_by_day.js.erb
document.querySelector('#show-tasks').innerHTML = '<%= j render partial: 'tasks/show_tasks.html.erb' %>'

app/views/tasks/task_update.js.erb
$('#show-edit-tasks-modal').modal('hide');
document.querySelector('#show-tasks').innerHTML = '<%= j render partial: 'tasks/show_tasks.html.erb' %>'

app/views/tasks/update_task_status.js.erb
document.querySelector('#show-tasks').innerHTML = '<%= j render partial: 'tasks/show_tasks', locals: { tasks: @tasks } %>';